# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: preprocessor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12preprocessor.proto\x12\x14\x66\x61st_ml_preprocessor\"~\n\x14PreprocessingRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tseparator\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\r\n\x05index\x18\x04 \x01(\x05\x12\x14\n\x0cproblem_type\x18\x05 \x01(\t\x12\x0c\n\x04mode\x18\x06 \x01(\t\"(\n\x15PreprocessingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x84\x01\n\x14PreprocessingService\x12l\n\x11PreprocessDataset\x12*.fast_ml_preprocessor.PreprocessingRequest\x1a+.fast_ml_preprocessor.PreprocessingResponseBf\n\x16\x63om.fastmlpreprocessorB\x17\x46\x61stMLPreprocessorProtoP\x01Z\x15\x66\x61stmlpreprocessorspb\xaa\x02\x19\x46\x61st.ML.Preprocessor.Grpcb\x06proto3')



_PREPROCESSINGREQUEST = DESCRIPTOR.message_types_by_name['PreprocessingRequest']
_PREPROCESSINGRESPONSE = DESCRIPTOR.message_types_by_name['PreprocessingResponse']
PreprocessingRequest = _reflection.GeneratedProtocolMessageType('PreprocessingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSINGREQUEST,
  '__module__' : 'preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:fast_ml_preprocessor.PreprocessingRequest)
  })
_sym_db.RegisterMessage(PreprocessingRequest)

PreprocessingResponse = _reflection.GeneratedProtocolMessageType('PreprocessingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSINGRESPONSE,
  '__module__' : 'preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:fast_ml_preprocessor.PreprocessingResponse)
  })
_sym_db.RegisterMessage(PreprocessingResponse)

_PREPROCESSINGSERVICE = DESCRIPTOR.services_by_name['PreprocessingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.fastmlpreprocessorB\027FastMLPreprocessorProtoP\001Z\025fastmlpreprocessorspb\252\002\031Fast.ML.Preprocessor.Grpc'
  _PREPROCESSINGREQUEST._serialized_start=44
  _PREPROCESSINGREQUEST._serialized_end=170
  _PREPROCESSINGRESPONSE._serialized_start=172
  _PREPROCESSINGRESPONSE._serialized_end=212
  _PREPROCESSINGSERVICE._serialized_start=215
  _PREPROCESSINGSERVICE._serialized_end=347
# @@protoc_insertion_point(module_scope)
