# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import preprocessor_pb2 as preprocessor__pb2


class PreprocessingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreprocessDataset = channel.unary_unary(
                '/fast_ml_preprocessor.PreprocessingService/PreprocessDataset',
                request_serializer=preprocessor__pb2.PreprocessingRequest.SerializeToString,
                response_deserializer=preprocessor__pb2.PreprocessingResponse.FromString,
                )


class PreprocessingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PreprocessDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreprocessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreprocessDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.PreprocessDataset,
                    request_deserializer=preprocessor__pb2.PreprocessingRequest.FromString,
                    response_serializer=preprocessor__pb2.PreprocessingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fast_ml_preprocessor.PreprocessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PreprocessingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PreprocessDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fast_ml_preprocessor.PreprocessingService/PreprocessDataset',
            preprocessor__pb2.PreprocessingRequest.SerializeToString,
            preprocessor__pb2.PreprocessingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
